# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mage/Evt-root/Evt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mage/Evt-root/Evt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mage/Evt-root/Evt/CMakeFiles /home/mage/Evt-root/Evt/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mage/Evt-root/Evt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named IoniEvt

# Build rule for target.
IoniEvt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IoniEvt
.PHONY : IoniEvt

# fast build rule for target.
IoniEvt/fast:
	$(MAKE) -f CMakeFiles/IoniEvt.dir/build.make CMakeFiles/IoniEvt.dir/build
.PHONY : IoniEvt/fast

#=============================================================================
# Target rules for targets named IoniEvt_static

# Build rule for target.
IoniEvt_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IoniEvt_static
.PHONY : IoniEvt_static

# fast build rule for target.
IoniEvt_static/fast:
	$(MAKE) -f CMakeFiles/IoniEvt_static.dir/build.make CMakeFiles/IoniEvt_static.dir/build
.PHONY : IoniEvt_static/fast

#=============================================================================
# Target rules for targets named PrimEvt

# Build rule for target.
PrimEvt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PrimEvt
.PHONY : PrimEvt

# fast build rule for target.
PrimEvt/fast:
	$(MAKE) -f CMakeFiles/PrimEvt.dir/build.make CMakeFiles/PrimEvt.dir/build
.PHONY : PrimEvt/fast

#=============================================================================
# Target rules for targets named PrimEvt_static

# Build rule for target.
PrimEvt_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PrimEvt_static
.PHONY : PrimEvt_static

# fast build rule for target.
PrimEvt_static/fast:
	$(MAKE) -f CMakeFiles/PrimEvt_static.dir/build.make CMakeFiles/PrimEvt_static.dir/build
.PHONY : PrimEvt_static/fast

#=============================================================================
# Target rules for targets named SecParticleEvt

# Build rule for target.
SecParticleEvt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SecParticleEvt
.PHONY : SecParticleEvt

# fast build rule for target.
SecParticleEvt/fast:
	$(MAKE) -f CMakeFiles/SecParticleEvt.dir/build.make CMakeFiles/SecParticleEvt.dir/build
.PHONY : SecParticleEvt/fast

#=============================================================================
# Target rules for targets named SecParticleEvt_static

# Build rule for target.
SecParticleEvt_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SecParticleEvt_static
.PHONY : SecParticleEvt_static

# fast build rule for target.
SecParticleEvt_static/fast:
	$(MAKE) -f CMakeFiles/SecParticleEvt_static.dir/build.make CMakeFiles/SecParticleEvt_static.dir/build
.PHONY : SecParticleEvt_static/fast

EventLib_Dict.o: EventLib_Dict.cxx.o
.PHONY : EventLib_Dict.o

# target to build an object file
EventLib_Dict.cxx.o:
	$(MAKE) -f CMakeFiles/SecParticleEvt.dir/build.make CMakeFiles/SecParticleEvt.dir/EventLib_Dict.cxx.o
	$(MAKE) -f CMakeFiles/SecParticleEvt_static.dir/build.make CMakeFiles/SecParticleEvt_static.dir/EventLib_Dict.cxx.o
.PHONY : EventLib_Dict.cxx.o

EventLib_Dict.i: EventLib_Dict.cxx.i
.PHONY : EventLib_Dict.i

# target to preprocess a source file
EventLib_Dict.cxx.i:
	$(MAKE) -f CMakeFiles/SecParticleEvt.dir/build.make CMakeFiles/SecParticleEvt.dir/EventLib_Dict.cxx.i
	$(MAKE) -f CMakeFiles/SecParticleEvt_static.dir/build.make CMakeFiles/SecParticleEvt_static.dir/EventLib_Dict.cxx.i
.PHONY : EventLib_Dict.cxx.i

EventLib_Dict.s: EventLib_Dict.cxx.s
.PHONY : EventLib_Dict.s

# target to generate assembly for a file
EventLib_Dict.cxx.s:
	$(MAKE) -f CMakeFiles/SecParticleEvt.dir/build.make CMakeFiles/SecParticleEvt.dir/EventLib_Dict.cxx.s
	$(MAKE) -f CMakeFiles/SecParticleEvt_static.dir/build.make CMakeFiles/SecParticleEvt_static.dir/EventLib_Dict.cxx.s
.PHONY : EventLib_Dict.cxx.s

SecParticleEvtLib_Dict.o: SecParticleEvtLib_Dict.cxx.o
.PHONY : SecParticleEvtLib_Dict.o

# target to build an object file
SecParticleEvtLib_Dict.cxx.o:
	$(MAKE) -f CMakeFiles/SecParticleEvt.dir/build.make CMakeFiles/SecParticleEvt.dir/SecParticleEvtLib_Dict.cxx.o
	$(MAKE) -f CMakeFiles/SecParticleEvt_static.dir/build.make CMakeFiles/SecParticleEvt_static.dir/SecParticleEvtLib_Dict.cxx.o
.PHONY : SecParticleEvtLib_Dict.cxx.o

SecParticleEvtLib_Dict.i: SecParticleEvtLib_Dict.cxx.i
.PHONY : SecParticleEvtLib_Dict.i

# target to preprocess a source file
SecParticleEvtLib_Dict.cxx.i:
	$(MAKE) -f CMakeFiles/SecParticleEvt.dir/build.make CMakeFiles/SecParticleEvt.dir/SecParticleEvtLib_Dict.cxx.i
	$(MAKE) -f CMakeFiles/SecParticleEvt_static.dir/build.make CMakeFiles/SecParticleEvt_static.dir/SecParticleEvtLib_Dict.cxx.i
.PHONY : SecParticleEvtLib_Dict.cxx.i

SecParticleEvtLib_Dict.s: SecParticleEvtLib_Dict.cxx.s
.PHONY : SecParticleEvtLib_Dict.s

# target to generate assembly for a file
SecParticleEvtLib_Dict.cxx.s:
	$(MAKE) -f CMakeFiles/SecParticleEvt.dir/build.make CMakeFiles/SecParticleEvt.dir/SecParticleEvtLib_Dict.cxx.s
	$(MAKE) -f CMakeFiles/SecParticleEvt_static.dir/build.make CMakeFiles/SecParticleEvt_static.dir/SecParticleEvtLib_Dict.cxx.s
.PHONY : SecParticleEvtLib_Dict.cxx.s

src/IoniEvt.o: src/IoniEvt.cc.o
.PHONY : src/IoniEvt.o

# target to build an object file
src/IoniEvt.cc.o:
	$(MAKE) -f CMakeFiles/IoniEvt.dir/build.make CMakeFiles/IoniEvt.dir/src/IoniEvt.cc.o
	$(MAKE) -f CMakeFiles/IoniEvt_static.dir/build.make CMakeFiles/IoniEvt_static.dir/src/IoniEvt.cc.o
.PHONY : src/IoniEvt.cc.o

src/IoniEvt.i: src/IoniEvt.cc.i
.PHONY : src/IoniEvt.i

# target to preprocess a source file
src/IoniEvt.cc.i:
	$(MAKE) -f CMakeFiles/IoniEvt.dir/build.make CMakeFiles/IoniEvt.dir/src/IoniEvt.cc.i
	$(MAKE) -f CMakeFiles/IoniEvt_static.dir/build.make CMakeFiles/IoniEvt_static.dir/src/IoniEvt.cc.i
.PHONY : src/IoniEvt.cc.i

src/IoniEvt.s: src/IoniEvt.cc.s
.PHONY : src/IoniEvt.s

# target to generate assembly for a file
src/IoniEvt.cc.s:
	$(MAKE) -f CMakeFiles/IoniEvt.dir/build.make CMakeFiles/IoniEvt.dir/src/IoniEvt.cc.s
	$(MAKE) -f CMakeFiles/IoniEvt_static.dir/build.make CMakeFiles/IoniEvt_static.dir/src/IoniEvt.cc.s
.PHONY : src/IoniEvt.cc.s

src/PrimEvt.o: src/PrimEvt.cc.o
.PHONY : src/PrimEvt.o

# target to build an object file
src/PrimEvt.cc.o:
	$(MAKE) -f CMakeFiles/PrimEvt.dir/build.make CMakeFiles/PrimEvt.dir/src/PrimEvt.cc.o
	$(MAKE) -f CMakeFiles/PrimEvt_static.dir/build.make CMakeFiles/PrimEvt_static.dir/src/PrimEvt.cc.o
.PHONY : src/PrimEvt.cc.o

src/PrimEvt.i: src/PrimEvt.cc.i
.PHONY : src/PrimEvt.i

# target to preprocess a source file
src/PrimEvt.cc.i:
	$(MAKE) -f CMakeFiles/PrimEvt.dir/build.make CMakeFiles/PrimEvt.dir/src/PrimEvt.cc.i
	$(MAKE) -f CMakeFiles/PrimEvt_static.dir/build.make CMakeFiles/PrimEvt_static.dir/src/PrimEvt.cc.i
.PHONY : src/PrimEvt.cc.i

src/PrimEvt.s: src/PrimEvt.cc.s
.PHONY : src/PrimEvt.s

# target to generate assembly for a file
src/PrimEvt.cc.s:
	$(MAKE) -f CMakeFiles/PrimEvt.dir/build.make CMakeFiles/PrimEvt.dir/src/PrimEvt.cc.s
	$(MAKE) -f CMakeFiles/PrimEvt_static.dir/build.make CMakeFiles/PrimEvt_static.dir/src/PrimEvt.cc.s
.PHONY : src/PrimEvt.cc.s

src/SecParticleEvt.o: src/SecParticleEvt.cc.o
.PHONY : src/SecParticleEvt.o

# target to build an object file
src/SecParticleEvt.cc.o:
	$(MAKE) -f CMakeFiles/SecParticleEvt.dir/build.make CMakeFiles/SecParticleEvt.dir/src/SecParticleEvt.cc.o
	$(MAKE) -f CMakeFiles/SecParticleEvt_static.dir/build.make CMakeFiles/SecParticleEvt_static.dir/src/SecParticleEvt.cc.o
.PHONY : src/SecParticleEvt.cc.o

src/SecParticleEvt.i: src/SecParticleEvt.cc.i
.PHONY : src/SecParticleEvt.i

# target to preprocess a source file
src/SecParticleEvt.cc.i:
	$(MAKE) -f CMakeFiles/SecParticleEvt.dir/build.make CMakeFiles/SecParticleEvt.dir/src/SecParticleEvt.cc.i
	$(MAKE) -f CMakeFiles/SecParticleEvt_static.dir/build.make CMakeFiles/SecParticleEvt_static.dir/src/SecParticleEvt.cc.i
.PHONY : src/SecParticleEvt.cc.i

src/SecParticleEvt.s: src/SecParticleEvt.cc.s
.PHONY : src/SecParticleEvt.s

# target to generate assembly for a file
src/SecParticleEvt.cc.s:
	$(MAKE) -f CMakeFiles/SecParticleEvt.dir/build.make CMakeFiles/SecParticleEvt.dir/src/SecParticleEvt.cc.s
	$(MAKE) -f CMakeFiles/SecParticleEvt_static.dir/build.make CMakeFiles/SecParticleEvt_static.dir/src/SecParticleEvt.cc.s
.PHONY : src/SecParticleEvt.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... IoniEvt"
	@echo "... IoniEvt_static"
	@echo "... PrimEvt"
	@echo "... PrimEvt_static"
	@echo "... SecParticleEvt"
	@echo "... SecParticleEvt_static"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... EventLib_Dict.o"
	@echo "... EventLib_Dict.i"
	@echo "... EventLib_Dict.s"
	@echo "... SecParticleEvtLib_Dict.o"
	@echo "... SecParticleEvtLib_Dict.i"
	@echo "... SecParticleEvtLib_Dict.s"
	@echo "... src/IoniEvt.o"
	@echo "... src/IoniEvt.i"
	@echo "... src/IoniEvt.s"
	@echo "... src/PrimEvt.o"
	@echo "... src/PrimEvt.i"
	@echo "... src/PrimEvt.s"
	@echo "... src/SecParticleEvt.o"
	@echo "... src/SecParticleEvt.i"
	@echo "... src/SecParticleEvt.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

